backend:   
  name: git-gateway   
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Food"
        name: "food"
        file: "content/food.md"
        fields:
          - label: Type
            name: type
            widget: hidden
            default: food
          - label: UniqueId
            name: uniqueid
            widget: hidden
            default: food
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Restos
            name: restos
            widget: list
            fields:
              - label: Resto
                name: resto
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Description, name: description, widget: markdown, required: false}
                  - {label: Image, name: img, widget: image, required: false}
  
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - label: Type
            name: type
            widget: hidden
            default: food
          - label: UniqueId
            name: uniqueid
            widget: hidden
            default: contact
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
            
      - label: "Line Up"
        name: "lineup"
        file: "content/lineup.md"
        fields:
          - {label: UniqueId, name: uniqueid, widget: hidden, default: artists}
          - {label: Type, name: type, widget: hidden, default: lineup}
          - {label: Title, name: title, widget: hidden}
          - {label: Intro, name: intro, widget: hidden}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
            
      - label: "Homepage"
        name: "index"
        file: "content/_index.md"
        fields:
          - label: UniqueId
            name: uniqueid
            widget: hidden
            default: home
          - label: Thumb Video
            name: imgvideo
            widget: image
          - label: Body
            name: body
            widget: markdown
            
      - label: "Partners"
        name: "partners"
        file: "content/partners.md"
        fields:
          - label: UniqueId
            name: uniqueid
            widget: hidden
            default: partners
          - label: Partner
            name: partner
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
              